
% SIMPS13  Computed the direct, Simpson's 1/3 rule, inverse Abel operator.
%  INVERSE operator, i.e., acts on deflections (A*b).
%  DIRECT or deflectometry operator, i.e., operates directly on deflections.
%  Assumes uniform annuli.
%  
%  D = kernel.simps13(NU) computes the 1D kernel with NU radial positions.
%  
%  D = kernel.simps13([NU,NV]) compute the 2D kernel with NU radial 
%  positions and NV axial positions. Kernel is generated by appropriately 
%  stacking the 1D kernels. 
%  
%  AUHTOR: Timothy Sipkens, 2020-02-18

function D = simps13(n)

Nu = n(1);

D = zeros(Nu, Nu);  % initialize D matrix

for ii=1:Nu
    for jj=1:Nu
        if jj>ii
            D(ii,jj) = (2 + (1 + (-1)^(jj-ii+1))) ./ ...
                sqrt((jj-1).^2 - (ii-1).^2);
            
        elseif jj==ii % for diagonal, extrapolate such that D_ii = D_i(i+1)
            D(ii,ii) = (2 + (1 + (-1)^(2))) ./ ...
                sqrt((ii).^2 - (ii-1).^2);
        end
    end
end
D = -1/(3*pi) .* D;

D(1,1) = 0;


% If second dimension, 
% use Kroneker to complete kernel.
if length(n)==2
    D = kron(speye(n(2)), D);
end

end
