
% TWO_PT  Computes the direct, two-point, inverse Abel operator.
%  INVERSE operator, i.e., acts on deflections (A*b).
%  DIRECT or deflectometry operator, i.e., operates directly on deflections.
%  More details are provided by Kohle and Agrawal, Appl. Opt. (2009).
%  Assumes uniform annuli.
%  
%  D = kernel.two_pt(NU) computes the 1D kernel with NU radial positions.
%  
%  D = kernel.two_pt([NU,NV]) compute the 2D kernel with NU radial 
%  positions and NV axial positions. Kernel is generated by appropriately 
%  stacking the 1D kernels. 
%  
%  AUTHOR: Timothy Sipkens, 2020-02-25

function D = two_pt(n)

Nu = n(1);

vec0 = 1:Nu;
[i,j] = ndgrid(vec0,vec0);

A = sqrt(j.^2-(i-1).^2)-...
    sqrt((j-1).^2-(i-1).^2);
B = log((j+sqrt(j.^2-(i-1).^2))./...
    (j-1+sqrt((j-1).^2-(i-1).^2)));

D = zeros(Nu, Nu);  % initialize D matrix

for ii=1:Nu
    for jj=1:Nu
        if jj==ii % diagonal, jj = ii = 1 condition is edited below
            D(ii,jj) = A(ii,jj) - jj * B(ii,jj);
            
        elseif jj>ii % above diagonal
            if jj==2 % special entries is jj = 2
                D(ii,jj) = (A(ii,jj) - jj * B(ii,jj) - 1);
            else
                D(ii,jj) = (A(ii,jj) - A(ii,jj-1)-...
                    jj * B(ii,jj) + (jj-2) * B(ii,jj-1));
            end
        end
    end
end
D(1,1) = 0; % jj = ii = 1 condition

D = 1/pi .* D; % incorporate 1/pi constant

D = sparse(D); % convert to sparse matrix for longer term storage


% If second dimension, 
% use Kroneker to complete kernel.
if length(n)==2
    D = kron(speye(n(2)), D);
end

end
